- list: "2023 赛季"
  file: "2023-all.json"
  init: "2023init.txt"
  contests:
    - name: "2023暑假个人赛1"
      date: "2023-07-09"
      file: "2023-07-09.txt"
      url: "https://vjudge.net/contest/567647"
    - name: "2023暑假个人赛2"
      date: "2023-07-10"
      file: "2023-07-10.txt"
      url: "https://vjudge.net/contest/567909"
    - name: "2023暑假个人赛3"
      date: "2023-07-11"
      file: "2023-07-11.txt"
      url: "https://vjudge.net/contest/568187"
    - name: "2023暑假个人赛4"
      date: "2023-08-05"
      file: "2023-08-05.txt"
      url: "https://vjudge.net/contest/573444"
    - name: "2023暑假个人赛5"
      date: "2023-08-12"
      file: "2023-08-12.txt"
      url: "https://vjudge.net/contest/574973"
    - name: "2023暑假个人赛6"
      date: "2023-08-21"
      file: "2023-08-21.txt"
      url: "https://vjudge.net/contest/576582"
    - name: "2023ZAFU十月校赛"
      date: "2023-10-15"
      file: "2023-10-15.txt"
      url: "#"
    - name: "浙师大周赛1"
      date: "2023-10-21"
      file: "2023-10-21.txt"
      url: "https://zjnu.qingyandark.top:88/contest/1299/view"
    - name: "浙师大周赛4"
      date: "2023-10-29"
      file: "2023-10-29.txt"
      url: "https://zjnu.qingyandark.top:88/contest/1306/view"
    - name: "浙师大周赛5"
      date: "2023-11-04"
      file: "2023-11-04.txt"
      url: "https://zjnu.qingyandark.top:88/contest/1309/view"
    - name: "ZAFU双周赛1"
      date: "2023-11-05"
      file: "2023-11-05.txt"
      url: "https://vjudge.net/contest/591462"
    - name: "浙师大周赛7"
      date: "2023-11-11"
      file: "2023-11-11.txt"
      url: "https://zjnu.qingyandark.top:88/contest/1316/view"
    - name: "ZAFU2023蓝桥杯选拔赛"
      date: "2023-11-19"
      file: "2023-11-19.txt"
      url: "https://ac.nowcoder.com/acm/contest/69527"
- list: "2022 赛季"
  file: "2022-all.json"
  init: "0000-00-00.txt"
  contests:
    - name: "2023寒假个人赛1"
      date: "2022-12-26"
      file: "2022-12-26.txt"
      url: "https://vjudge.net/contest/535688"
    - name: "2023寒假个人赛2"
      date: "2022-12-30"
      file: "2022-12-30.txt"
      url: "https://vjudge.net/contest/536171"
    - name: "2023寒假个人赛3"
      date: "2023-01-04"
      file: "2023-01-04.txt"
      url: "https://vjudge.net/contest/536683"
    - name: "2023寒假个人赛4"
      date: "2023-01-11"
      file: "2023-01-11.txt"
      url: "https://vjudge.net/contest/538025"
    - name: "2023寒假个人赛5"
      date: "2023-02-26"
      file: "2023-02-26.txt"
      url: "https://vjudge.net/contest/541518"
    - name: "2023双周赛1"
      date: "2023-05-07"
      file: "2023-05-07.txt"
      url: "https://vjudge.net/contest/554896"
    - name: "浙师大五月训练赛"
      date: "2023-05-13"
      file: "2023-05-13.txt"
      url: "https://zjnu.qingyandark.cn/contest/1275/standing"
    - name: "2023机器人校赛"
      date: "2023-05-21"
      file: "2023-05-21.txt"
      url: "#"
    - name: "杭师大训练赛"
      date: "2023-05-27"
      file: "2023-05-27.txt"
      url: "#"
- list: "2021 赛季"
  init: '0000-00-00.txt'
  file: "2021-all.json"
  contests: []
