- list: "2022 赛季"
  file: "2022-all.json"
  contests:
    - name: "2023寒假个人赛1"
      date: "2022-12-26"
      file: "2022-12-26.txt"
      url: "https://vjudge.net/contest/535688"
    - name: "2023寒假个人赛2"
      date: "2022-12-30"
      file: "2022-12-30.txt"
      url: "https://vjudge.net/contest/536171"
    - name: "2023寒假个人赛3"
      date: "2023-01-04"
      file: "2023-01-04.txt"
      url: "https://vjudge.net/contest/536683"
    - name: "2023寒假个人赛4"
      date: "2023-01-11"
      file: "2023-01-11.txt"
      url: "https://vjudge.net/contest/538025"
    - name: "2023寒假个人赛5"
      date: "2023-02-26"
      file: "2023-02-26.txt"
      url: "https://vjudge.net/contest/541518"
    - name: "2023双周赛1"
      date: "2023-05-07"
      file: "2023-05-07.txt"
      url: "https://vjudge.net/contest/554896"
    - name: "浙师大五月训练赛"
      date: "2023-05-13"
      file: "2023-05-13.txt"
      url: "https://zjnu.qingyandark.cn/contest/1275/standing"
    - name: "2023机器人校赛"
      date: "2023-05-21"
      file: "2023-05-21.txt"
      url: "#"
    - name: "杭师大训练赛"
      date: "2023-05-27"
      file: "2023-05-27.txt"
      url: "#"
- list: "2021 赛季"
  file: "2021-all.json"
  contests: []
